version: '3.8'
services:
  cache_redis:
    image: redis:alpine
    container_name: meu-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # <--- Isso garante que o cache não suma mesmo reiniciando

volumes:
  redis_data: